/**
 * Created by timxiong on 2018/3/16.
 * 删除class名称
 * document.getElementsByClassName("bg")[0].className = "title"
 */
module.exports=[
    {
        name:'开奖公告',
        icon:'ios-trophy-outline',
        url:'http://m.aicai.com/kjgg/index.do?agentId=1&vt=5',
        desc:'走势分析一网打尽',
        color:'#25A9FF'
    },
    {
        name:'我的收藏',
        icon:'ios-star-outline',
        url:'',
        desc:'走势分析一网打尽',
        color:'#FF5D3B'
    },
    {
        name:'预测资讯',
        icon:'ios-list-box-outline',
        url:'http://m.aicai.com/newInfo/index.do?navId=2&agentId=1&vt=5',
        desc:'走势分析一网打尽',
        color:'#FF2D55'
    },
    {
        name:'赛事比分',
        icon:'ios-football',
        url:'http://m.aicai.com/league/zc/match/fbMatchListView?agentId=1&vt=5',
        desc:'走势分析一网打尽',
        color:'#46BC62'
    },
    {
        name:'精品杀码',
        icon:'ios-person',
        url:'http://m.aicai.com/f/filterCode.do?gameId=101&agentId=1&vt=5'
    },
    {
        name:'走势图表',
        icon:'md-trending-up',
        url:'http://m.aicai.com/zst/index.do?agentId=1&vt=5'
    },

    {
        name:'阅读记录',
        icon:'md-star',
        url:'',
    }
]